### ISSUE TITLE
new images looks broken

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/rabbitmq-docker#34]
two issues on the latest images.
- folder update dot 3.7.13 althouth the actual version of rabbitmq is still 3.7.9, pretty confusing...
- /plugins points to non-exiting folder which is /usr/lib/rabbitmq/lib/rabbitmq_server-3.7.13/plugins
as the actual folder that exist is /usr/lib/rabbitmq/lib/rabbitmq_server-3.7.9/plugins

we are looking on latest images exits on gcr marketplace.
- gcr.io/cloud-marketplace/google/rabbitmq3
- gcr.io/cloud-marketplace/google/rabbitmq

are we missing something?
10x
chen

**Comment by ovk6** [comment]
Hi, @lechen26 

Thank you for notice. Images were fixed and updated to use consistent versions.
