### ISSUE TITLE
tune mnesia parameter

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/rabbitmq-docker#42]
Hi

is it possible to tune Mnesia write parameter?
i'm trying to set dump_log_write_threshold for mnesia to be higher then the default value of 100 records and seems like i cannot find the right parameter on the sysctl config format.

is there any way to update this parameter using this image?

thanks
Chen

**Comment by lechen26** [comment]
found the way to do so using advanced.config with erlang format

**Comment by vladvintila** [comment]
```
[
{rabbit, [{dump_log_write_threshold, 1000}]}
].
```
Worked for me. Posted here since there's not much info out there how to do this, and this issue helped.
