### ISSUE TITLE
rabbitmq latest 3.7 broken?

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/rabbitmq-docker#43]
Hi

seems like the latest 3.7 image is still broken.

the prometheus plugin added to the image but i think there is a missing plugin which is 
prometheus_process_collector-1.4.3.ez, hence the rabbit log fill with errors of the exporter plugin.

can it be please fixed?

thanks
Chen

**Comment by lechen26** [comment]
create PR add prometheus_process_collector plugin #44

**Comment by lechen26** [comment]
also any reason why not using the latest prometheus version (v3.7.9.1) ?

**Comment by lechen26** [comment]
@armandomiani  can you help with that?

**Comment by ovk6** [comment]
Hello @lechen26 

prometheus_process_collector plugin added (#49) and latest prometheus exporter version updated (#50).

Thank you for filing this issue.
