### ISSUE TITLE
Latest update broke the image

### ISSUE THREAD

**Issue by TomKriek** [GoogleCloudPlatform/rabbitmq-docker#55]
Since a few days ago the image fails to boot properly, I get the following errors on k8s

`/usr/local/bin/docker-entrypoint.sh: line 391: rabbitmq-plugins: command not found
/usr/local/bin/docker-entrypoint.sh: line 437: exec: rabbitmq-server: not found
`

Enabled plugins are: '[rabbitmq_management,rabbitmq_management_agent,rabbitmq_web_dispatch].'

Output from `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by TomKriek** [comment]
It seems as though the `$PATH` hasn't been set correctly. During launch.

**Comment by armandomiani** [comment]
Hello @TomKriek ,

Can you please detail further how the deployment was realized? 

From my side, I just tested from master, and all deployment types are running properly.
* Container: https://github.com/GoogleCloudPlatform/rabbitmq-docker
* Kubernetes: https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/k8s/rabbitmq
* GCP Marketplace: https://console.cloud.google.com/marketplace/details/google/rabbitmq

Can you also provide the full image reference you are using?

Thanks

**Comment by armandomiani** [comment]
As per lack of response we're closing the issue. Additionally, RabbitMQ was totally rebuilt and upgraded. Please check it out again and let us know if everything is working from your side. 

Containers:
* gcr.io/cloud-marketplace/google/rabbitmq3:3.8
* gcr.io/cloud-marketplace/google/rabbitmq3:3.7
